version: "3.9"

networks:
  database:
    driver: bridge
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    restart: unless-stopped
    networks:
      - database
    ports:
      - "5432:5432"
    volumes:
      - "/persistentVolume0/data:/data"
      - "/persistentVolume1/wal:/wal"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_INITDB_WALDIR=/wal
      - PGDATA=/data
  postgresql-check:
    container_name: postgresql-check
    image: nanoscaledev/postgresql-check:latest
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - database
    ports:
      - "26726:26726"
    environment: 
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=password